# Generated by Django 3.2.9 on 2021-12-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20211202_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
