# Generated by Django 3.2.9 on 2021-12-12 12:17

import core.validators
import datetime
from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_students_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='enroll_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='students',
            name='graduate_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='students',
            name='birthday',
            field=models.DateField(default=datetime.date.today, validators=[core.validators.AdultValidator(20)]),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, validators=[students.validators.phone_number_validator]),
        ),
    ]
