# Generated by Django 3.2.9 on 2021-12-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_groups_avg_life_expectancy_groups_members_qty'),
        ('students', '0005_auto_20211212_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.groups'),
        ),
    ]
