# Generated by Django 3.2.9 on 2022-01-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='group',
        ),
    ]
