# Generated by Django 3.2.9 on 2021-12-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_subject_teachers_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='address',
            new_name='subject',
        ),
    ]
