# Generated by Django 3.2.9 on 2022-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20220105_1212'),
        ('teachers', '0002_remove_teachers_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='group',
            field=models.ManyToManyField(related_name='groups_teachers', to='groups.Groups'),
        ),
    ]
