# Generated by Django 3.2.9 on 2021-12-08 19:31

from django.db import migrations, models
import teachers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_rename_address_teachers_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[teachers.validators.phone_number_validator]),
        ),
    ]
