# Generated by Django 3.2.9 on 2021-12-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groups_headman'),
        ('teachers', '0004_teachers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='groups.groups'),
        ),
    ]
