# Generated by Django 3.2.9 on 2021-11-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_name', models.CharField(max_length=100)),
                ('groups_nationality', models.CharField(max_length=100)),
                ('groups_language', models.CharField(max_length=100)),
                ('groups_avg_life_expectancy', models.IntegerField()),
            ],
        ),
    ]
