# Generated by Django 3.2.9 on 2021-12-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='groups_avg_life_expectancy',
            new_name='members_qty',
        ),
    ]
