# Generated by Django 3.2.9 on 2021-12-23 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groups_headman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='groups_nationality',
            new_name='groups_country',
        ),
    ]
