# Generated by Django 3.2.9 on 2021-12-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_group'),
        ('groups', '0002_rename_groups_avg_life_expectancy_groups_members_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='headman',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headman_group', to='students.students'),
        ),
    ]
